### PR TITLE
avoid global define which is problematic

### PR DESCRIPTION
**Pull request by bung87**
ref: https://github.com/yglukhov/darwin/issues/20

### CODE REVIEW

**Comment by yglukhov** [comment]
Can we close this thanks to your fix in nim https://github.com/nim-lang/Nim/pull/22382?

**Comment by bung87** [comment]
yes, we can, just my patch make generated c code without `preInitProc` section. it's better than before.

**Comment by yglukhov** [comment]
Well that was exactly the point. So that calling a class method would not call `objc_getClass` every time.

**Comment by bung87** [comment]
oh, that's nice, close then.

**Pull request closed without merging**
