### PR TITLE
add missing types

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by yglukhov** [comment]
Thank you!

**Comment by bung87** [comment]
can you do the arm64 support ? I tried here, but get confused. https://github.com/yglukhov/darwin/compare/master...bung87:darwin:arm64
`msgSend` no stret dispatchers on `arm64`
https://opensource.apple.com/source/objc4/objc4-647/test/msgSend.m.auto.html

**Comment by yglukhov** [comment]
I'm not using a mac currently, so can't promise a timeframe. But all the objc lowlevel machinery was tested with iphones a while ago, which is arm64, so it should just work? Or is macos somehow different?

**Comment by yglukhov** [comment]
If you just build your code with this lib on arm macos as is, what behavior do you observe?

**Comment by bung87** [comment]
first is the msgSend no stret dispatchers on arm64 thing like comment above.

second the msgSend proc type seems wrong which will cause nil access in my program.
https://developer.apple.com/documentation/apple-silicon/porting-your-macos-apps-to-apple-silicon

**Pull request merged**
